### ISSUE TITLE
Error thrown when using es6 import

### ISSUE THREAD

**Issue by mberende** [silvermine/videojs-quality-selector#67] opened 2020-09-21 13:27 UTC
using the latest version of videojs and latest version of the plugin.
my code looks like this

import videojs from `'video.js';`
import QualitySelector from "@silvermine/videojs-quality-selector";
QualitySelector(videojs);

The error I am getting:

class.js:5 Uncaught TypeError: Cannot set property 'Class' of undefined
    at class.js:5
    at Object../node_modules/class.extend/lib/class.js (class.js:62)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/@silvermine/videojs-quality-selector/src/js/util/SafeSeek.js (SafeSeek.js:3)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/@silvermine/videojs-quality-selector/src/js/index.js (index.js:7)
    at __webpack_require__ (bootstrap:19)
......

**Comment by axten** [comment] 2020-09-21 15:08
Found out that the problem is strict mode. atm this plugin cannot be used when using your bundle as a es6+ module in the browser (<script type="module">).

**Comment by jthomerson** [comment] 2020-09-21 16:10
@axten @mberende thanks. Do you have any suggested changes? We won't have much time to look at this for a while, so if you have a viable workaround, you'll probably need to use that for now.

**Comment by axten** [comment] 2020-09-21 16:13
For now, we switched back to normal script tags but in order to solve that, I think there is just one solution: replace/remove class.extend lib.

**Comment by mberende** [comment] 2020-09-22 06:15
> Found out that the problem is strict mode. atm this plugin cannot be used when using your bundle as an es6+ module in the browser (<script type="module">).

@axten Thanks! If I switch back to normal script tags then I cannot use other es 6 modules which my project is currently using. Any other workaround for this ?

**Comment by ignacio-dev** [comment] 2022-08-31 12:58
Hello, was this ever solved? I am currently facing this issue with Vite in Laravel.. works fine on dev, but throws this error on build

**Comment by ignacio-dev** [comment] 2022-08-31 16:45
Any fixes on this? I am currently using Vite with Laravel, which makes this plugin unusable for me..

**Comment by dwassing** [comment] 2023-02-07 08:54
This is still an issue as of today. The change that yokuze mentioned still needs to be merged into this repo. I was looking to possibly smoothly integrate this quality controller into an existing application but the lack of ES6 compatibility prompts me to build my own quick fix instead.

**Comment by yokuze** [comment] 2023-11-21 15:34
This is addressed in v1.3.1 of this plugin. Thanks!

**Closed by yokuze** 2023-11-21 15:34 UTC
