### ISSUE TITLE
Mobile tap on quality selector icon, works inconsistently

### ISSUE THREAD

**Issue by tylik1** [silvermine/videojs-quality-selector#18] opened 2018-03-14 09:51 UTC
Hi, thanks for an awesome plugin!

One thing you might consider to fix is toggling quality popup, on clicking the quality selector icon.
It opens as expected, but second tap doesn't alway close popup. Also when you tap on the video itself, the popup is supposed to close, but sometimes it works, and sometimes doesn't.

Checked on Android 7, Galaxy S7 edge

**Comment by hack4mer** [comment] 2018-09-27 06:17
Hi, I'm facing the same issue and going to contribute a fix for this

**Comment by onebytegone** [comment] 2018-10-04 13:40
@hack4mer Thanks for the update! I am able to reproduce the issue now. It also appears that pressing and holding the MenuButton for a short bit causes the issue as well. However, using [this demo](https://codepen.io/onebytegone/full/jeOeNZ) I'm seeing a similar behavior with the built-in subtitles selector. Since this plugin doesn't implement any custom MenuButton hiding/showing logic, it seems the actual bug might be in Video.js.

I haven't had much time to investigate the root cause here. However looking through the Video.js issues/PRs, https://github.com/videojs/video.js/pull/5465 was recently opened with regards https://github.com/videojs/video.js/issues/1690 and https://github.com/videojs/video.js/issues/5404. I'm curious to see if that fixes the issue. Can't really say for sure though, since the actual cause of this issue hasn't been determined yet.

**Closed** 2019-11-20 18:48 UTC
